/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nodeunify.jupiter.kafka;

import org.junit.Test;
import static org.junit.Assert.*;

public class KafkaProducerAppTest {
    @Test
    public void testAppHasAGreeting() {
        KafkaProducerApp classUnderTest = new KafkaProducerApp();
    }
}
